### ISSUE TITLE
Inconsistency on python 3.6 versions in CI environments

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3206]
I have 2 failed tests when testing locally on python 3.6.9 which do not happen on the CI.

- `geotrek.zoning.tests.test_views.LandLayersViewsTest.test_views_status`
- `geotrek.zoning.tests.test_views.RestrictedAreaViewsTest.test_views_status_is_200_when_type_known`

Both failed on error: `ValueError: unsupported pickle protocol: 5`

To reproduce run the test suite inside a docker container based on `makinacorpus/geodjango:bionic-3.8`.

I noticed that the CI on Github Actions uses an environment Ubuntu-18.04 + python3.6 to run the test suites. This leads to python 3.6.15 being used. But the latest version of python-3.6 on Ubuntu-18.04 is 3.6.9. Maybe that is the cause.

So maybe we should we pin the PATCH version for python-3.6 on the CI:
```yaml
strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        tests-env: ['tests', 'tests_nds']
        include:
          - os: ubuntu-18.04
            python-version: 3.6.9  # default python version in 18.04
          - os: ubuntu-20.04
            python-version: 3.8  # default python version in 20.04
```
